# =============================================================================
# Generate inst/schemas/munsell.json -- the slim schema used by the
# photo -> Munsell route.
#
# extract_munsell_from_photo() asks a vision model for colour only, but it used
# to inject the FULL horizon schema (35 properties/horizon, ~3,200 tokens). On
# Groq's free tier that alone consumed 45% of the 8,000-token-per-minute budget
# and a real photo could not fit beside it.
#
# This derives a strict SUBSET of inst/schemas/horizon.json, so the field
# definitions can never drift from the canonical ones. `additionalProperties`
# is unrestricted in horizon.json, so a response carrying extra fields still
# validates -- the subset only stops us *demanding* attributes a photograph
# cannot show.
#
# Run with:  Rscript data-raw/generate_munsell_schema.R
# =============================================================================

KEEP <- c("top_cm", "bottom_cm", "designation", "munsell_moist", "munsell_dry")

src <- jsonlite::fromJSON("inst/schemas/horizon.json", simplifyVector = FALSE)
props <- src$properties$horizons$items$properties
missing <- setdiff(KEEP, names(props))
if (length(missing))
  stop("horizon.json lacks: ", paste(missing, collapse = ", "))

out <- src
out$title <- "soilKey Munsell-from-photo extraction"
out$description <- paste(
  "Slim subset of the horizon schema for the photo -> Munsell route:",
  "horizon geometry, designation and Munsell colour only.",
  "Generated by data-raw/generate_munsell_schema.R -- do not edit by hand.")
out$properties$horizons$items$properties <- props[KEEP]

jsonlite::write_json(out, "inst/schemas/munsell.json",
                     auto_unbox = TRUE, pretty = TRUE, null = "null")

before <- file.info("inst/schemas/horizon.json")$size
after  <- file.info("inst/schemas/munsell.json")$size
cat(sprintf("munsell.json: %d fields, %d bytes (was %d; ~%d tokens saved)\n",
            length(KEEP), after, before, round((before - after) / 4)))
