# Write inst/rules/wrb2022/qualifiers.yaml from the Chapter 4 lists that
# data-raw/wrb2022_ch4_lists.py extracts from the WRB 2022 PDF:
#
#   python3 data-raw/wrb2022_ch4_lists.py /tmp/wrb2022.txt /tmp/wrb2022_ch4.json
#   python3 data-raw/wrb2022_qualifiers_yaml.py /tmp/wrb2022_ch4.json inst/rules/wrb2022/qualifiers.yaml
#
# Every list is copied as printed in Chapter 4: principal qualifiers in their
# ranked order (with Haplic last where Chapter 4 lists it), supplementary
# qualifiers as listed, and alternatives separated by a slash kept together as
# one entry ("Rhodic/Xanthic"). The naming rules that
# turn these lists into a name (Chapter 2.2) live in resolve_wrb_qualifiers().
import json, sys

ORDER = [  # the WRB 2022 key order, with the page of each RSG's list
    ("HS", "HISTOSOLS", 95), ("AT", "ANTHROSOLS", 96), ("TC", "TECHNOSOLS", 97),
    ("CR", "CRYOSOLS", 98), ("LP", "LEPTOSOLS", 99), ("SN", "SOLONETZ", 100),
    ("VR", "VERTISOLS", 101), ("SC", "SOLONCHAKS", 102), ("GL", "GLEYSOLS", 103),
    ("AN", "ANDOSOLS", 104), ("PZ", "PODZOLS", 105), ("PT", "PLINTHOSOLS", 106),
    ("PL", "PLANOSOLS", 107), ("ST", "STAGNOSOLS", 108), ("NT", "NITISOLS", 109),
    ("FR", "FERRALSOLS", 110), ("CH", "CHERNOZEMS", 111), ("KS", "KASTANOZEMS", 112),
    ("PH", "PHAEOZEMS", 113), ("UM", "UMBRISOLS", 114), ("DU", "DURISOLS", 115),
    ("GY", "GYPSISOLS", 116), ("CL", "CALCISOLS", 117), ("RT", "RETISOLS", 118),
    ("AC", "ACRISOLS", 119), ("LX", "LIXISOLS", 120), ("AL", "ALISOLS", 121),
    ("LV", "LUVISOLS", 122), ("CM", "CAMBISOLS", 123), ("FL", "FLUVISOLS", 124),
    ("AR", "ARENOSOLS", 125), ("RG", "REGOSOLS", 126),
]

HEADER = '''version: "WRB 2022 (4th ed.) -- principal and supplementary qualifiers per RSG, Chapter 4"
implementation_status: "soilKey v0.9.217 -- the 32 lists copied from Chapter 4 of the corrected text (18 December 2022)"
source: |
  IUSS Working Group WRB (2022). World Reference Base for Soil
  Resources, 4th edition. International Union of Soil Sciences, Vienna.
  Chapter 4 (key to the RSGs with their lists of principal and
  supplementary qualifiers), Chapter 5 (qualifier definitions), Chapter 2.2
  (rules for naming soils).

# Generated by data-raw/wrb2022_qualifiers_yaml.py from the lists that
# data-raw/wrb2022_ch4_lists.py reads off the WRB 2022 PDF. Do not edit by
# hand: regenerate, so the lists stay auditable against the text.
#
# principal:     ranked, as in Chapter 4. Haplic, last where it is listed,
#                applies when no other principal qualifier does. 16 RSGs do
#                not list it (their last entry, e.g. Dystric/Eutric, applies
#                to any soil with the data), so their name has no Haplic.
# supplementary: as listed in Chapter 4 (texture qualifiers first).
# "A/B":         alternatives that are mutually exclusive, or where the later
#                one is redundant; only the first one that applies is used.
#
# How a name is built from these lists (Chapter 2.2) is in
# resolve_wrb_qualifiers(): principal qualifiers are written right to left,
# the first one in the list next to the RSG name; supplementary qualifiers go
# in brackets, texture first, the rest in alphabetical order.
# Until v0.9.216 these lists were not Chapter 4's: most followed the longer
# WRB 2014 lists (Ferralsols had 30 principal qualifiers against WRB 2022's 13).

rsg_qualifiers:
'''

def flow(key, items, indent):
    lead = " " * indent + key + ": ["
    col = len(lead)
    lines, cur = [], ""
    for i, t in enumerate(items):
        piece = t + ("," if i < len(items) - 1 else "")
        cand = (cur + " " + piece) if cur else piece
        if col + len(cand) + 1 > 79 and cur:
            lines.append(cur); cur = piece
        else:
            cur = cand
    lines.append(cur)
    return lead + ("\n" + " " * col).join(lines) + "]\n"

ch4 = json.load(open(sys.argv[1]))
out = HEADER
for code, name, page in ORDER:
    lists = ch4[name]
    principal = lists["principal"]
    supplementary = lists["supplementary"]
    out += "\n  %s:   # %s (WRB 2022 Ch 4, p. %d)\n" % (code, name.capitalize(), page)
    out += flow("principal", principal, 4)
    out += flow("supplementary", supplementary, 4)
open(sys.argv[2], "w").write(out)
print("wrote", sys.argv[2], "with", len(ORDER), "RSGs")
